(rrpsdev) C:\Users\HBD2KOR\digital.git\rrps\python\rrps.dt.integrator.sapbomasbuilt>rrps-dt-integrator-sapbomasbuilt cfg
\integrator.cfg.yml cfg\integrator2.ini
2019-07-31 11:09:45,646 WARNING [ioticlabs.dt.common.util] {MainThread} No logging configuration specified
2019-07-31 11:09:45,666 INFO [IoticAgent.IOT.Client] {MainThread} Core version: 0.6.9
2019-07-31 11:09:45,666 INFO [IoticAgent.IOT.Client] {MainThread} IOT version: 0.6.9
2019-07-31 11:09:45,667 INFO [IoticAgent.Core.Client] {MainThread} ubjson version: 0.13.0 (extension enabled)
2019-07-31 11:09:45,679 INFO [ioticlabs.dt.api.event.registry] {MainThread} Loaded 25 event types
2019-07-31 11:09:49,639 INFO [IoticAgent.Core.Client] {MainThread} QAPI version: 1.2.1
2019-07-31 11:09:49,642 INFO [IoticAgent.IOT.Client] {MainThread} create_thing(lid="integrator01")
2019-07-31 11:09:49,822 WARNING [IoticAgent.IOT.Client] {tp-0} Created thing integrator01 assigned to different agent: N
one
2019-07-31 11:09:49,823 WARNING [IoticAgent.Core.ThreadPool] {tp-0} Call failed: __cb_duplicated
Traceback (most recent call last):
  File "c:\users\hbd2kor\envs\rrpsdev\lib\site-packages\IoticAgent\IOT\Client.py", line 748, in create_thing
    return self.__new_things.pop(lid)
KeyError: 'integrator01'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\HBD2KOR\envs\rrpsdev\Scripts\rrps-dt-integrator-sapbomasbuilt-script.py", line 11, in <module>
    load_entry_point('rrps.dt.integrator.sapbomasbuilt', 'console_scripts', 'rrps-dt-integrator-sapbomasbuilt')()
  File "c:\users\hbd2kor\digital.git\rrps\python\rrps.dt.integrator.sapbomasbuilt\rrps\dt\integrator\sapbomasbuilt\__mai
n__.py", line 9, in main
    main_run('RRPS SAP BOM As Built Integrator', SAPBomAsBuiltIntegrator)
  File "c:\users\hbd2kor\envs\rrpsdev\lib\site-packages\rrps\dt\common\__init__.py", line 90, in main_run
    integrator.run()
  File "c:\users\hbd2kor\envs\rrpsdev\lib\site-packages\IoticAgent\ThingRunner.py", line 83, in run
    self.__run()
  File "c:\users\hbd2kor\envs\rrpsdev\lib\site-packages\IoticAgent\ThingRunner.py", line 104, in __run
    if self.__handle_exception(ctx):
  File "c:\users\hbd2kor\envs\rrpsdev\lib\site-packages\IoticAgent\ThingRunner.py", line 94, in __run
    self.on_startup()
  File "c:\users\hbd2kor\digital.git\rrps\python\rrps.dt.integrator.sapbomasbuilt\rrps\dt\integrator\sapbomasbuilt\impl.
py", line 103, in on_startup
    self.__integrator.start()
  File "c:\users\hbd2kor\envs\rrpsdev\lib\site-packages\ioticlabs\dt\api\integrator\__init__.py", line 174, in start
    self.__create_thing()
  File "c:\users\hbd2kor\envs\rrpsdev\lib\site-packages\ioticlabs\dt\api\integrator\__init__.py", line 380, in __create_
thing
    NestedConfig.get(cfg.raw, 'thing.lid', check=NestedConfig.Check.non_empty_str)
  File "c:\users\hbd2kor\envs\rrpsdev\lib\site-packages\IoticAgent\IOT\Client.py", line 750, in create_thing
    raise raise_from(IOTClientError('Thing %s not in cache (post-create)' % lid), ex)
  File "<string>", line 2, in raise_from
IoticAgent.IOT.Exceptions.IOTClientError: Thing integrator01 not in cache (post-create)

(rrpsdev) C:\Users\HBD2KOR\digital.git\rrps\python\rrps.dt.integrator.sapbomasbuilt>





051MYoXO7jY3{aMUFTBgYm



                        field('Upvalto', 'string', doc='removal'),
                        field('Upvalfr', 'string', doc='installation')





  426  git merge master 
  427  git checkout master 
  428  git add .idea/workspace.xml 
  429  git checkout master 
  430  git rm .idea/workspace.xml 
  431  git rm -f .idea/workspace.xml 
  432  git checkout master 
  433  git merge --no-ff branch
  434  git merge --no-ff branch